# Makefile for the EXCESS data structures framework.

# Makefile
DIRS=testbench SpBLAS

all: $(DIRS)
	cd testbench; $(MAKE) all
	cd SpBLAS; $(MAKE) all

clean:
	cd testbench; $(MAKE) clean
	cd SpBLAS; $(MAKE) clean
#	@rm
