#!/bin/sh -f
# name of the job
#PBS -N excess_cluster_mandelbrot_CASETHREADS_threads
# use the complete path to the standard output files
#PBS -o /nas_home/andersg/EXCESS-software/data-structures-framework/PBS/mandelbrot_job/$PBS_JOBID.out
#PBS -e /nas_home/andersg/EXCESS-software/data-structures-framework/PBS/mandelbrot_job/$PBS_JOBID.err 
# set walltime: max. 00:10:00 for the queue 'batch' and max. 01:00:00 for the queue 'night'
#PBS -l walltime=01:00:00
# set the queue: batch or night
#PBS -q night
# set the number of nodes 
#PBS -l nodes=1:node01:ppn=20
# use submission enviroment - please don't change
#pbs -V
#start job from the directory it was submitted
#cd $PBS_WORKDIR
date
echo "PBS_O_HOST=$PBS_O_HOST  # The name of the host upon which the qsub command is running."
echo "PBS_O_WORKDIR=$PBS_O_WORKDIR  # The absolute path of the current working directory of the qsub command."
echo "PBS_JOBID=$PBS_JOBID  # The job identifier assigned to the job by the batch system."
echo "PBS_JOBNAME=$PBS_JOBNAME     # The job name supplied by the user."

#load used modules
. $HOME/.modules

# load module power/mf_shared
# and get the new dbkey from the monitoring framework
module load power/mf_shared
DBKEY=$( get_unique_dbkey -d ${HOME}/.mf/dbkey/ -f ${PBS_JOBID} )
echo "Monitoring framework $DBKEY"

# Job environment
export JOBDIR=/nas_home/andersg/EXCESS-software/data-structures-framework/PBS/mandelbrot_job/
export LOGDIR=/nas_home/andersg/results/mandelbrot_`date +%Y-%m-%d_%H.%M`

mkdir $LOGDIR
cd $LOGDIR

###############################################################################
echo "job is starting"

export LOGBASE=mandelbrot_result_`date +%Y-%m-%d_%H.%M`
export RMAINLOG=$LOGDIR/$LOGBASE-out.txt

echo "PBS job $PBS_JOBID is starting..." >> $RMAINLOG
echo "Monitoring framework $DBKEY" >> $RMAINLOG

PROGRAM=$HOME/EXCESS-software/data-structures-framework/testbench

# The actual frequency on the HLRS cluster is unknown.
# Probably 2.9GHz with potential TurboBoost to 3.8GHz. 
FREQUENCIES="3"
#FREQUENCIES="3.4Ghz 2.3Ghz 1.2Ghz"
#THREADS="2 4 6 8 10 12 14 16"
THREADS="CASETHREADS"
# The total case duration is 2 + $KILLDURATION + 3 seconds.
# $KILLDURATION must be sufficiently larger than $PRGDURATION or
# the case may be terminated prematurely.
KILLDURATION="40"
SAMPLEDURATION="44"
REPEATS="1"
#   0. Queue NOBLE Lock-Free DB          1. Queue NOBLE Lock-Free DU
#   2. Queue NOBLE Lock-Free SB          3. Queue NOBLE Lock-Free BB
#   4. Queue NOBLE Lock-Free BASKET      5. Queue NOBLE Lock-Free ELIM
#   6. Queue NOBLE Lock-Based            7. Queue TBB concurrent_queue
#   8. Stack NOBLE Lock-Free B           9. Stack NOBLE Lock-Free ELIM
#   10. Bag NOBLE Lock-Free BB          11. Pool NOBLE Lock-Free EDTREE
#ALGORITHMS="0 1 2 3 4 5 6 7 8 9 10 11"
ALGORITHMS="CASEALG"
# Patterns:
#   0. N/2 Producer - N/2 Consumer threads. CPU-heavy producers
PATTERNS="0"
# Contention: 0. 2x2; 1. 4x4; 2. 8x8; 3. 16x16; ...
CONTENTIONS="0 1 2 3"
# Pinning: -1. NONE. (default);        0.  FILL PU per socket;
#           1.  FILL CORE per socket;  2.  JUMP socket.
PINNING="1"

export RAPLSAMPLE="$HOME/EXCESS-software/state-record-tool/read-rapl-likwid -s 10 -d $SAMPLEDURATION"
export TEMPSAMPLE="$HOME/EXCESS-software/state-record-tool/read-coretemp -d $SAMPLEDURATION"

for Frequency in $FREQUENCIES; do
    # Set the CPU frequency.
    likwid-setFrequencies -f $Frequency

    sleep 5s
    echo Verifying CPU frequency setting.
    likwid-setFrequencies -p
    sleep 5s

    for Iter in $REPEATS; do
        for Threads in $THREADS; do
            for Pattern in $PATTERNS; do
                for Contention in $CONTENTIONS; do
                    for Alg in $ALGORITHMS; do
                        Case=a$Alg-p$Pattern-c$Contention-f$Frequency-t$Threads-$Iter
                        echo "Starting $LOGBASE-$Case ..."

                        RRAPLLOG=$LOGDIR/$LOGBASE-RAPL-$Case.csv
                        RTEMPLOG=$LOGDIR/$LOGBASE-TEMP-$Case.csv
                        RCACHELOG=$LOGDIR/$LOGBASE-CACHE-$Case.txt
                        ROUTLOG=$LOGDIR/$LOGBASE-OUT-$Case.txt
                        
                        # Start sampling
                        ($RAPLSAMPLE -o $RRAPLLOG)&
                        #($TEMPSAMPLE -o $RTEMPLOG)&
                        echo >> $RMAINLOG; echo >> $RMAINLOG;
                        date >> $RMAINLOG; echo $Case >> $RMAINLOG

                        echo "$PROGRAM -e 1 -p $PINNING -t $Threads -i $Alg -s 0 $Pattern -s 1 $Contention" >> $RMAINLOG
                        sleep 2s

                        $PROGRAM -e 1 -p $PINNING -t $Threads -i $Alg -s 0 $Pattern -s 1 $Contention 2>> $RMAINLOG > $ROUTLOG & (sleep $KILLDURATION; killall $PROGRAM &>> $RMAINLOG)

                        echo "... done"
                        sleep 3s
                        echo " "
                    done
                done
            done
        done
    done
done

sleep 30s

###############################################################################
echo "job is done"
